apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: swagger-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    kubernetes.io/ingress.class: "nginx"
  labels:
    app: swagger
  namespace: myapp
spec:
  rules:
    - http:
        paths:
          - path: /swagger
            backend:
              serviceName: swagger-service
              servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: swagger-service
  namespace: myapp
spec:
  selector:
    app: swagger
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: swagger
  namespace: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swagger
  template:
    metadata:
      labels:
        app: swagger
    spec:
      containers:
        - name: swagger
          image: swaggerapi/swagger-ui
          imagePullPolicy: Never
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
