apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: redoc-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    # nginx.ingress.kubernetes.io/ssl-redirect: "false"
    # nginx.ingress.kubernetes.io/ssl-redirect: "false"
    # kubernetes.io/ingress.class: "nginx"
    # nginx.ingress.kubernetes.io/enable-cors: "true"
  labels:
    app: redoc
  # namespace: myapp
spec:
  type: NodePort
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: redoc-service
              servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redoc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redoc
  template:
    metadata:
      labels:
        app: redoc
    spec:
      containers:
        - name: redoc
          image: myredoc:1.0.1
          imagePullPolicy: Never
          ports:
          - name: http
            containerPort: 80
            protocol: TCP
          - name: https
            containerPort: 443
            protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: redoc-service
spec:
  selector:
    app: redoc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
